---
github_organization_name: fabianorosas
github_bot_name:
github_bot_user_name:
github_bot_email:

ghprb_admin_user:
ghprb_admin_organization:

centos_alternate_mirror_release_url:

upload_server_host_name: localhost
upload_server_user_name: root
upload_server_builds_dir_path: /tmp/builds_dir
upload_server_weekly_dir_path: /tmp/weekly_dir
